function newG1 = reduce2nNetwork(newG)

newG1 = (newG(1:length(newG)/2 , 1:length(newG)/2)  + ...
         newG(1:length(newG)/2 , 1 + (length(newG)/2) : length(newG)) +...
            newG(1 + (length(newG)/2) : length(newG) , 1:length(newG)/2) + ... 
            newG(1 + (length(newG)/2) : length(newG) , 1 + (length(newG)/2) : length(newG))) > 0;